# 주한공관주소록의 한글 국가명 → (영문명, ISO 3166-1 alpha-2).
# 원본에 영문 표기가 전혀 없어 수기로 매핑한다. 국제기구는 여기 없고 ORGS 로 뺀다.
COUNTRIES = {
 "가나":("Ghana","GH"), "가봉":("Gabon","GA"), "과테말라":("Guatemala","GT"),
 "교황청":("Holy See (Vatican)","VA"), "그리스":("Greece","GR"), "나이지리아":("Nigeria","NG"),
 "남아프리카공화국":("South Africa","ZA"), "네덜란드":("Netherlands","NL"), "네팔":("Nepal","NP"),
 "노르웨이":("Norway","NO"), "뉴질랜드":("New Zealand","NZ"), "덴마크":("Denmark","DK"),
 "도미니카공화국":("Dominican Republic","DO"), "독일":("Germany","DE"), "동티모르":("Timor-Leste","TL"),
 "라오스":("Laos","LA"), "라트비아":("Latvia","LV"), "러시아":("Russia","RU"),
 "레바논":("Lebanon","LB"), "루마니아":("Romania","RO"), "룩셈부르크":("Luxembourg","LU"),
 "르완다":("Rwanda","RW"), "리비아":("Libya","LY"), "리투아니아":("Lithuania","LT"),
 "마셜 제도":("Marshall Islands","MH"), "말레이시아":("Malaysia","MY"), "멕시코":("Mexico","MX"),
 "모로코":("Morocco","MA"), "모리타니아":("Mauritania","MR"), "몽골":("Mongolia","MN"),
 "미국":("United States","US"), "미얀마":("Myanmar","MM"), "바레인":("Bahrain","BH"),
 "방글라데시":("Bangladesh","BD"), "베네수엘라":("Venezuela","VE"), "베트남":("Vietnam","VN"),
 "벨기에":("Belgium","BE"), "벨라루스":("Belarus","BY"), "볼리비아":("Bolivia","BO"),
 "불가리아":("Bulgaria","BG"), "브라질":("Brazil","BR"), "브루나이":("Brunei","BN"),
 "사우디아라비아":("Saudi Arabia","SA"), "세네갈":("Senegal","SN"), "세르비아":("Serbia","RS"),
 "수단":("Sudan","SD"), "스리랑카":("Sri Lanka","LK"), "스웨덴":("Sweden","SE"),
 "스위스":("Switzerland","CH"), "스페인":("Spain","ES"), "슬로바키아":("Slovakia","SK"),
 "슬로베니아":("Slovenia","SI"), "시에라리온":("Sierra Leone","SL"), "싱가포르":("Singapore","SG"),
 "아랍에미리트":("United Arab Emirates","AE"), "아르헨티나":("Argentina","AR"),
 "아일랜드":("Ireland","IE"), "아제르바이잔":("Azerbaijan","AZ"), "아프가니스탄":("Afghanistan","AF"),
 "알제리":("Algeria","DZ"), "앙골라":("Angola","AO"), "에스토니아":("Estonia","EE"),
 "에콰도르":("Ecuador","EC"), "에티오피아":("Ethiopia","ET"), "엘살바도르":("El Salvador","SV"),
 "영국":("United Kingdom","GB"), "오만":("Oman","OM"), "오스트리아":("Austria","AT"),
 "온두라스":("Honduras","HN"), "요르단":("Jordan","JO"), "우루과이":("Uruguay","UY"),
 "우즈베키스탄":("Uzbekistan","UZ"), "우크라이나":("Ukraine","UA"), "이라크":("Iraq","IQ"),
 "이란":("Iran","IR"), "이스라엘":("Israel","IL"), "이집트":("Egypt","EG"),
 "이탈리아":("Italy","IT"), "인도":("India","IN"), "인도네시아":("Indonesia","ID"),
 "일본":("Japan","JP"), "잠비아":("Zambia","ZM"), "조지아":("Georgia","GE"),
 "중국":("China","CN"), "체코":("Czechia","CZ"), "칠레":("Chile","CL"),
 "카자흐스탄":("Kazakhstan","KZ"), "카타르":("Qatar","QA"), "캄보디아":("Cambodia","KH"),
 "캐나다":("Canada","CA"), "케냐":("Kenya","KE"), "코스타리카":("Costa Rica","CR"),
 "코트디부아르":("Côte d'Ivoire","CI"), "콜롬비아":("Colombia","CO"),
 "콩고(D.R.)":("DR Congo","CD"), "쿠바":("Cuba","CU"), "쿠웨이트":("Kuwait","KW"),
 "크로아티아":("Croatia","HR"), "키르기스스탄":("Kyrgyzstan","KG"), "타지키스탄":("Tajikistan","TJ"),
 "탄자니아":("Tanzania","TZ"), "태국":("Thailand","TH"), "투르크메니스탄":("Turkmenistan","TM"),
 "튀니지":("Tunisia","TN"), "튀르키예":("Türkiye","TR"), "파나마":("Panama","PA"),
 "파라과이":("Paraguay","PY"), "파키스탄":("Pakistan","PK"), "파푸아뉴기니":("Papua New Guinea","PG"),
 "페루":("Peru","PE"), "포르투갈":("Portugal","PT"), "폴란드":("Poland","PL"),
 "프랑스":("France","FR"), "핀란드":("Finland","FI"), "필리핀":("Philippines","PH"),
 "헝가리":("Hungary","HU"), "호주":("Australia","AU"),
 "유럽연합":("European Union","EU"),
}
